# Generated by Django 2.1.7 on 2019-08-05 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse_FF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_following', models.IntegerField(null=True, verbose_name='is_following')),
                ('is_follower', models.IntegerField(null=True, verbose_name='is_follower')),
            ],
        ),
        migrations.CreateModel(
            name='Assistants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_type', models.IntegerField(verbose_name='assistant_type')),
                ('number_of_actions', models.IntegerField(verbose_name='number_of_actions')),
            ],
        ),
        migrations.CreateModel(
            name='Assistants_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_followers', models.IntegerField(verbose_name='min_followers')),
                ('max_followers', models.IntegerField(verbose_name='max_followers')),
                ('min_followings', models.IntegerField(verbose_name='min_followings')),
                ('max_followings', models.IntegerField(verbose_name='max_followings')),
                ('min_posts', models.IntegerField(verbose_name='min_posts')),
                ('biography', models.IntegerField(verbose_name='biography')),
                ('is_hidden', models.IntegerField(verbose_name='hidden_account')),
                ('is_bussines', models.IntegerField(verbose_name='is_bussines')),
            ],
        ),
        migrations.CreateModel(
            name='Assistants_Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_as_a_source', models.TextField(verbose_name='user_as_a_source')),
                ('hashtag_as_a_source', models.TextField(verbose_name='user_as_a_source')),
                ('location_as_a_source', models.TextField(verbose_name='user_as_a_source')),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Assistants')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='comment')),
                ('status', models.IntegerField(null=True, verbose_name='status')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='update_time')),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Assistants')),
            ],
        ),
        migrations.CreateModel(
            name='Follow_Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(null=True, verbose_name='status')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='update_time')),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Assistants')),
            ],
        ),
        migrations.CreateModel(
            name='IG_Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(null=True, verbose_name='post_id')),
                ('post_user', models.CharField(max_length=200, null=True, verbose_name='post_user')),
            ],
        ),
        migrations.CreateModel(
            name='IG_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True, verbose_name='username')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name='full_name')),
                ('pk_number', models.IntegerField(null=True, verbose_name='pk_number')),
                ('profile_pic_url', models.CharField(max_length=300, null=True, verbose_name='profile_pic_url')),
                ('number_of_followers', models.IntegerField(null=True, verbose_name='number_of_followers')),
                ('number_of_followings', models.IntegerField(null=True, verbose_name='number_of_followings')),
                ('biography', models.IntegerField(null=True, verbose_name='biography')),
                ('is_business', models.IntegerField(null=True, verbose_name='is_business')),
                ('is_hidden', models.IntegerField(null=True, verbose_name='is_hidden')),
                ('number_of_medias', models.IntegerField(null=True, verbose_name='number_of_medias')),
            ],
        ),
        migrations.CreateModel(
            name='Instagram_Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True, verbose_name='username')),
                ('password', models.CharField(max_length=200, null=True, verbose_name='password')),
                ('is_current_account', models.IntegerField(null=True, verbose_name='is current account')),
                ('cookie', models.TextField(null=True, verbose_name='cookie')),
                ('main_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instagram_Accounts_Analyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(null=True, verbose_name='like_count')),
                ('post_count', models.IntegerField(null=True, verbose_name='post_count')),
                ('comment_count', models.IntegerField(null=True, verbose_name='comment_count')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='update_time')),
                ('instagram_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Instagram_Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Licanse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_licanse', models.CharField(max_length=200, null=True, verbose_name='Type of Licanse')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Register Date')),
                ('main_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like_Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(null=True, verbose_name='status')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='update_time')),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Assistants')),
                ('ig_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.IG_Posts')),
            ],
        ),
        migrations.AddField(
            model_name='follow_actions',
            name='ig_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.IG_Users'),
        ),
        migrations.AddField(
            model_name='comment_actions',
            name='ig_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.IG_Posts'),
        ),
        migrations.AddField(
            model_name='assistants_settings',
            name='instagram_accout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Instagram_Accounts'),
        ),
        migrations.AddField(
            model_name='assistants',
            name='instagram_accout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Instagram_Accounts'),
        ),
        migrations.AddField(
            model_name='analyse_ff',
            name='ig_user_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.IG_Users'),
        ),
        migrations.AddField(
            model_name='analyse_ff',
            name='instagram_account_analyse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Instagram_Accounts_Analyse'),
        ),
    ]
