# Generated by Django 2.1.7 on 2019-08-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant_Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=200, null=True, verbose_name='Hashtag')),
                ('posters', models.IntegerField(verbose_name='Posters')),
                ('likers', models.IntegerField(verbose_name='Likers')),
                ('commenters', models.IntegerField(verbose_name='Commenters')),
            ],
        ),
        migrations.CreateModel(
            name='Assistant_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='Location')),
                ('posters', models.IntegerField(verbose_name='Posters')),
                ('likers', models.IntegerField(verbose_name='Likers')),
                ('commenters', models.IntegerField(verbose_name='Commenters')),
            ],
        ),
        migrations.CreateModel(
            name='Assistant_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True, verbose_name='Username')),
                ('followers', models.IntegerField(verbose_name='Followers')),
                ('followings', models.IntegerField(verbose_name='Followings')),
                ('likers', models.IntegerField(verbose_name='Likers')),
                ('commenters', models.IntegerField(verbose_name='Commenters')),
            ],
        ),
        migrations.RemoveField(
            model_name='Assistants_Sources',
            name='assistant',
        ),
        migrations.RemoveField(
            model_name='assistants',
            name='assistant_type',
        ),
        migrations.RemoveField(
            model_name='assistants_settings',
            name='instagram_accout',
        ),
        migrations.AddField(
            model_name='Assistants',
            name='assistant_action_type',
            field=models.IntegerField(null=True, verbose_name='Assistant_action_type'),
        ),
        migrations.AddField(
            model_name='Assistants',
            name='assistant_source_type',
            field=models.IntegerField(null=True, verbose_name='Assistant_source_type'),
        ),
        migrations.AddField(
            model_name='Assistants_Settings',
            name='assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Assistants'),
        ),
        migrations.DeleteModel(
            name='Assistants_Sources',
        ),
        migrations.AddField(
            model_name='Assistant_User',
            name='assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Assistants'),
        ),
        migrations.AddField(
            model_name='Assistant_Location',
            name='assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Assistants'),
        ),
        migrations.AddField(
            model_name='Assistant_Hashtag',
            name='assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aristo.Assistants'),
        ),
    ]
