# Generated by Django 2.1.7 on 2019-08-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristo', '0002_auto_20190806_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistants',
            old_name='instagram_accout',
            new_name='instagram_account',
        ),
    ]
