# Generated by Django 2.1.7 on 2019-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristo', '0003_auto_20190806_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant_user',
            name='own',
            field=models.IntegerField(null=True, verbose_name='Own'),
        ),
        migrations.AddField(
            model_name='assistants_settings',
            name='max_posts',
            field=models.IntegerField(null=True, verbose_name='max_posts'),
        ),
        migrations.AlterField(
            model_name='assistant_hashtag',
            name='commenters',
            field=models.IntegerField(null=True, verbose_name='Commenters'),
        ),
        migrations.AlterField(
            model_name='assistant_hashtag',
            name='likers',
            field=models.IntegerField(null=True, verbose_name='Likers'),
        ),
        migrations.AlterField(
            model_name='assistant_hashtag',
            name='posters',
            field=models.IntegerField(null=True, verbose_name='Posters'),
        ),
        migrations.AlterField(
            model_name='assistant_location',
            name='commenters',
            field=models.IntegerField(null=True, verbose_name='Commenters'),
        ),
        migrations.AlterField(
            model_name='assistant_location',
            name='likers',
            field=models.IntegerField(null=True, verbose_name='Likers'),
        ),
        migrations.AlterField(
            model_name='assistant_location',
            name='posters',
            field=models.IntegerField(null=True, verbose_name='Posters'),
        ),
        migrations.AlterField(
            model_name='assistant_user',
            name='commenters',
            field=models.IntegerField(null=True, verbose_name='Commenters'),
        ),
        migrations.AlterField(
            model_name='assistant_user',
            name='followers',
            field=models.IntegerField(null=True, verbose_name='Followers'),
        ),
        migrations.AlterField(
            model_name='assistant_user',
            name='followings',
            field=models.IntegerField(null=True, verbose_name='Followings'),
        ),
        migrations.AlterField(
            model_name='assistant_user',
            name='likers',
            field=models.IntegerField(null=True, verbose_name='Likers'),
        ),
        migrations.AlterField(
            model_name='assistants',
            name='number_of_actions',
            field=models.IntegerField(null=True, verbose_name='number_of_actions'),
        ),
        migrations.AlterField(
            model_name='assistants_settings',
            name='biography',
            field=models.IntegerField(null=True, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='assistants_settings',
            name='is_bussines',
            field=models.IntegerField(null=True, verbose_name='is_bussines'),
        ),
        migrations.AlterField(
            model_name='assistants_settings',
            name='is_hidden',
            field=models.IntegerField(null=True, verbose_name='hidden_account'),
        ),
        migrations.AlterField(
            model_name='assistants_settings',
            name='max_followers',
            field=models.IntegerField(null=True, verbose_name='max_followers'),
        ),
        migrations.AlterField(
            model_name='assistants_settings',
            name='max_followings',
            field=models.IntegerField(null=True, verbose_name='max_followings'),
        ),
        migrations.AlterField(
            model_name='assistants_settings',
            name='min_followers',
            field=models.IntegerField(null=True, verbose_name='min_followers'),
        ),
        migrations.AlterField(
            model_name='assistants_settings',
            name='min_followings',
            field=models.IntegerField(null=True, verbose_name='min_followings'),
        ),
        migrations.AlterField(
            model_name='assistants_settings',
            name='min_posts',
            field=models.IntegerField(null=True, verbose_name='min_posts'),
        ),
    ]
