# Generated by Django 2.1.7 on 2019-08-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristo', '0005_auto_20190806_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistants_settings',
            old_name='is_busines',
            new_name='is_business',
        ),
    ]
