# Generated by Django 2.1.7 on 2019-08-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristo', '0007_api_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram_accounts',
            name='cookie',
        ),
    ]
