# Generated by Django 2.2.4 on 2019-08-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristo', '0008_remove_instagram_accounts_cookie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_settings',
            name='main_user',
        ),
    ]
